version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    environment:
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    command: ["node", "app/index.js"]

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
        VITE_GOOGLE_CLIENT_SECRET: ${VITE_GOOGLE_CLIENT_SECRET}
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
